name             'endpoint'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures endpoint'
long_description 'Installs/Configures endpoint'
version          '0.1.0'

depends 'chocolatey'
depends 'windows'
